## Word Embeddings

In [ ]:
!pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.8/27.8 MB 61.7 MB/s eta 0:00:00


In [ ]:
from gensim.models import Word2Vec
import numpy as np

In [ ]:
sentences = [
    ["the", "cat", "sat"],
    ["the", "dog", "ran"],
    ["the", "cat", "ran"],
    ["the", "dog", "sat"]
]

In [ ]:
# Train Word2Vec
model = Word2Vec(
    sentences=sentences,
    vector_size=4,
    window=2,
    min_count=1,
    workers=1
)

In [ ]:
# Sequence we want to encode
sequence = ["the", "cat", "sat"]

In [ ]:
# Convert every word into its Word2Vec vector
encoded_sequence = np.array([
    model.wv[word] for word in sequence
])

In [ ]:
print(encoded_sequence)
print(encoded_sequence.shape)

[[-0.01340568  0.00591078  0.12758374  0.22523183]
 [ 0.07191449  0.02479684 -0.20713037 -0.23622045]
 [-0.11341533  0.16385129 -0.12150401 -0.04540044]]
(3, 4)
